# Generated by Django 6.0.6 on 2026-06-09 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buku', '0001_initial'),
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField()),
                ('jatuh_tempo', models.DateField()),
                ('keperluan', models.TextField()),
                ('status', models.CharField(choices=[('Dipinjam', 'Dipinjam'), ('Dikembalikan', 'Dikembalikan'), ('Terlambat', 'Terlambat')], default='Dipinjam', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buku.buku')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
            ],
            options={
                'db_table': 'peminjaman',
                'ordering': ['-created_at'],
            },
        ),
    ]
