# Generated by Django 6.0.4 on 2026-06-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='petugas',
            field=models.CharField(default='Budi Siregar', max_length=100),
        ),
    ]
