# Generated by Django 6.0.6 on 2026-06-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('pengarang', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('Novel', 'Novel'), ('Sejarah', 'Sejarah'), ('Pendidikan', 'Pendidikan')], max_length=50)),
                ('penerbit', models.CharField(max_length=100)),
                ('tahun_terbit', models.IntegerField()),
                ('rak', models.CharField(choices=[('Rak A-01', 'Rak A-01'), ('Rak A-02', 'Rak A-02'), ('Rak A-03', 'Rak A-03'), ('Rak A-04', 'Rak A-04'), ('Rak A-05', 'Rak A-05')], max_length=20)),
                ('stok', models.IntegerField(default=0)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'buku',
                'ordering': ['-created_at'],
            },
        ),
    ]
