# Generated by Django 6.0.4 on 2026-06-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
