# Generated by Django 6.0.4 on 2026-06-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_buku_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buku',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='buku',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='buku',
            name='judul',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='buku',
            name='kategori',
            field=models.CharField(choices=[('Novel', 'Novel'), ('Sejarah', 'Sejarah'), ('Pendidikan', 'Pendidikan'), ('Fiksi', 'Fiksi'), ('Fantasi', 'Fantasi'), ('Pengembangan Diri', 'Pengembangan Diri'), ('Autobiografi', 'Autobiografi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='buku',
            name='penerbit',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='buku',
            name='pengarang',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='buku',
            name='rak',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='buku',
            name='stok',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buku',
            name='tahun_terbit',
            field=models.IntegerField(db_column='tahun_terbit'),
        ),
    ]
